In [4]:
import sys
!{sys.executable} -m pip install faker

Defaulting to user installation because normal site-packages is not writeable
Collecting faker
  Downloading faker-40.28.1-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: tzdata in c:\programdata\anaconda3\lib\site-packages (from faker) (2025.2)
Downloading faker-40.28.1-py3-none-any.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------- ----------------------------- 0.5/2.1 MB 3.3 MB/s eta 0:00:01
   --------------- ------------------------ 0.8/2.1 MB 2.5 MB/s eta 0:00:01
   ------------------------- -------------- 1.3/2.1 MB 2.2 MB/s eta 0:00:01
   ------------------------------ --------- 1.6/2.1 MB 2.0 MB/s eta 0:00:01
   ------------------------------ --------- 1.6/2.1 MB 2.0 MB/s eta 0:00:01
   ---------------------------------------- 2.1/2.1 MB 1.5 MB/s eta 0:00:00
Installing collected packages: faker
Successfully installed faker-40.28.1

  WARNING: The script faker.exe is installed in 'C:\Users\singl\AppData\Roaming\Python\Python313\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

In [5]:
import pandas as pd
from faker import Faker
import random

fake = Faker()

print(fake.name())
print(fake.email())

Ashley Stewart
fergusonpaul@example.net

In [6]:
import pandas as pd
from faker import Faker
import random

fake = Faker()

print(fake.name())
print(fake.email())

Nicole Jimenez
brittanyduran@example.org

In [13]:
customers = []

for i in range(1000):
    customers.append({
        "customer_id": f"C{i+1:03}",
        "customer_name": fake.name(),
        "email": fake.email(),
        "registration_date": fake.date_between(start_date="-2y", end_date="today"),
        "customer_type": random.choice(["REGULAR", "PREMIUM", "VIP"])
    })

customers

[{'customer_id': 'C001',
  'customer_name': 'Janice Sherman',
  'email': 'alyssawhite@example.org',
  'registration_date': datetime.date(2025, 12, 18),
  'customer_type': 'PREMIUM'},
 {'customer_id': 'C002',
  'customer_name': 'Stephanie Gonzalez',
  'email': 'vbaker@example.org',
  'registration_date': datetime.date(2024, 12, 30),
  'customer_type': 'PREMIUM'},
 {'customer_id': 'C003',
  'customer_name': 'Yolanda Hernandez DVM',
  'email': 'rpratt@example.com',
  'registration_date': datetime.date(2024, 7, 25),
  'customer_type': 'PREMIUM'},
 {'customer_id': 'C004',
  'customer_name': 'Brandi Gay',
  'email': 'rogersruth@example.net',
  'registration_date': datetime.date(2025, 4, 19),
  'customer_type': 'PREMIUM'},
 {'customer_id': 'C005',
  'customer_name': 'Samantha Pearson',
  'email': 'blevine@example.org',
  'registration_date': datetime.date(2026, 3, 12),
  'customer_type': 'REGULAR'},
 {'customer_id': 'C006',
  'customer_name': 'Leslie Rowland',
  'email': 'dakotalogan@example.net',
  'registration_date': datetime.date(2026, 1, 9),
  'customer_type': 'PREMIUM'},
 {'customer_id': 'C007',
  'customer_name': 'Michael Duke',
  'email': 'anthonybrooks@example.net',
  'registration_date': datetime.date(2026, 3, 21),
  'customer_type': 'REGULAR'},
 {'customer_id': 'C008',
  'customer_name': 'Gary Flores',
  'email': 'henry97@example.org',
  'registration_date': datetime.date(2025, 1, 1),
  'customer_type': 'REGULAR'},
 {'customer_id': 'C009',
  'customer_name': 'Kelly Newman',
  'email': 'nguyenmichael@example.org',
  'registration_date': datetime.date(2025, 7, 31),
  'customer_type': 'VIP'},
 {'customer_id': 'C010',
  'customer_name': 'Paula Richards',
  'email': 'kevinhernandez@example.com',
  'registration_date': datetime.date(2026, 7, 6),
  'customer_type': 'REGULAR'},
 {'customer_id': 'C011',
  'customer_name': 'Crystal Jackson',
  'email': 'amanda05@example.net',
  'registration_date': datetime.date(2025, 7, 19),
  'customer_type': 'VIP'},
 {'customer_id': 'C012',
  'customer_name': 'Hannah Stanton',
  'email': 'kenneth65@example.com',
  'registration_date': datetime.date(2026, 4, 14),
  'customer_type': 'REGULAR'},
 {'customer_id': 'C013',
  'customer_name': 'Ronnie Gonzalez',
  'email': 'jamesgarcia@example.net',
  'registration_date': datetime.date(2026, 6, 26),
  'customer_type': 'PREMIUM'},
 {'customer_id': 'C014',
  'customer_name': 'Donna Davis',
  'email': 'obriennicole@example.com',
  'registration_date': datetime.date(2025, 9, 21),
  'customer_type': 'REGULAR'},
 {'customer_id': 'C015',
  'customer_name': 'Alyssa Williams',
  'email': 'roserebecca@example.net',
  'registration_date': datetime.date(2026, 5, 6),
  'customer_type': 'VIP'},
 {'customer_id': 'C016',
  'customer_name': 'Brian Mitchell',
  'email': 'gphillips@example.net',
  'registration_date': datetime.date(2026, 5, 1),
  'customer_type': 'PREMIUM'},
 {'customer_id': 'C017',
  'customer_name': 'Colin Hutchinson',
  'email': 'aaron76@example.org',
  'registration_date': datetime.date(2024, 11, 29),
  'customer_type': 'PREMIUM'},
 {'customer_id': 'C018',
  'customer_name': 'Vincent Kane',
  'email': 'hannah64@example.org',
  'registration_date': datetime.date(2025, 3, 8),
  'customer_type': 'VIP'},
 {'customer_id': 'C019',
  'customer_name': 'Ronald Miller',
  'email': 'greerpatrick@example.org',
  'registration_date': datetime.date(2025, 12, 26),
  'customer_type': 'VIP'},
 {'customer_id': 'C020',
  'customer_name': 'Catherine Mcpherson',
  'email': 'michaellopez@example.org',
  'registration_date': datetime.date(2025, 10, 19),
  'customer_type': 'REGULAR'},
 {'customer_id': 'C021',
  'customer_name': 'Elizabeth Jones',
  'email': 'wbush@example.com',
  'registration_date': datetime.date(2025, 2, 11),
  'customer_type': 'VIP'},
 {'customer_id': 'C022',
  'customer_name': 'Jacqueline Sullivan',
  'email': 'jodi40@example.org',
  'registration_date': datetime.date(2025, 4, 14),
  'customer_type': 'PREMIUM'},
 {'customer_id': 'C023',
  'customer_name': 'Darrell Williams',
  'email': 'jeremiahmassey@example.com',
  'registration_date': datetime.date(2024, 9, 22),
  'customer_type': 'VIP'},
 {'customer_id': 'C024',
  'customer_name': 'Charles Taylor',
  'email': 'hillemily@example.com',
  'registration_date': datetime.date(2025, 5, 22),
  'customer_type': 'REGULAR'},
 {'customer_id': 'C025',
  'customer_name': 'Jeffrey Wallace',
  'email': 'howardjoanne@example.com',
  'registration_date': datetime.date(2025, 8, 11),
  'customer_type': 'VIP'},
 {'customer_id': 'C026',
  'customer_name': 'Carl Garcia',
  'email': 'ethan81@example.net',
  'registration_date': datetime.date(2024, 10, 15),
  'customer_type': 'PREMIUM'},
 {'customer_id': 'C027',
  'customer_name': 'Donald West',
  'email': 'deborah10@example.org',
  'registration_date': datetime.date(2025, 3, 6),
  'customer_type': 'PREMIUM'},
 {'customer_id': 'C028',
  'customer_name': 'Daniel Harrison',
  'email': 'candacecarrillo@example.org',
  'registration_date': datetime.date(2025, 6, 5),
  'customer_type': 'PREMIUM'},
 {'customer_id': 'C029',
  'customer_name': 'Kristin Marks',
  'email': 'zwilliams@example.org',
  'registration_date': datetime.date(2025, 9, 9),
  'customer_type': 'REGULAR'},
 {'customer_id': 'C030',
  'customer_name': 'Cody Thornton',
  'email': 'amandasmith@example.org',
  'registration_date': datetime.date(2026, 6, 1),
  'customer_type': 'PREMIUM'},
 {'customer_id': 'C031',
  'customer_name': 'Andrew Rodriguez',
  'email': 'ryan20@example.net',
  'registration_date': datetime.date(2026, 1, 15),
  'customer_type': 'PREMIUM'},
 {'customer_id': 'C032',
  'customer_name': 'Paul Cox',
  'email': 'lewismelinda@example.org',
  'registration_date': datetime.date(2025, 7, 1),
  'customer_type': 'REGULAR'},
 {'customer_id': 'C033',
  'customer_name': 'Troy Johnson',
  'email': 'flowersandrew@example.org',
  'registration_date': datetime.date(2025, 6, 1),
  'customer_type': 'VIP'},
 {'customer_id': 'C034',
  'customer_name': 'Jasmine Hammond',
  'email': 'mariagibbs@example.com',
  'registration_date': datetime.date(2026, 7, 4),
  'customer_type': 'VIP'},
 {'customer_id': 'C035',
  'customer_name': 'Brandon Dodson',
  'email': 'wjohnson@example.net',
  'registration_date': datetime.date(2026, 4, 30),
  'customer_type': 'PREMIUM'},
 {'customer_id': 'C036',
  'customer_name': 'Daniel Montes',
  'email': 'reyesvictoria@example.org',
  'registration_date': datetime.date(2025, 1, 17),
  'customer_type': 'PREMIUM'},
 {'customer_id': 'C037',
  'customer_name': 'Carol Myers',
  'email': 'jacksonanne@example.com',
  'registration_date': datetime.date(2026, 6, 8),
  'customer_type': 'VIP'},
 {'customer_id': 'C038',
  'customer_name': 'Bruce Alvarez',
  'email': 'andersonbrianna@example.com',
  'registration_date': datetime.date(2025, 4, 12),
  'customer_type': 'VIP'},
 {'customer_id': 'C039',
  'customer_name': 'Teresa Cobb',
  'email': 'sosalawrence@example.org',
  'registration_date': datetime.date(2025, 8, 29),
  'customer_type': 'VIP'},
 {'customer_id': 'C040',
  'customer_name': 'Steven Castillo',
  'email': 'walkertracy@example.net',
  'registration_date': datetime.date(2025, 11, 3),
  'customer_type': 'PREMIUM'},
 {'customer_id': 'C041',
  'customer_name': 'Dawn Garcia',
  'email': 'harristerri@example.com',
  'registration_date': datetime.date(2025, 1, 4),
  'customer_type': 'REGULAR'},
 {'customer_id': 'C042',
  'customer_name': 'Kathleen Gomez',
  'email': 'campbelltimothy@example.org',
  'registration_date': datetime.date(2026, 5, 26),
  'customer_type': 'PREMIUM'},
 {'customer_id': 'C043',
  'customer_name': 'Laura Daniels',
  'email': 'sanderssarah@example.com',
  'registration_date': datetime.date(2025, 6, 19),
  'customer_type': 'REGULAR'},
 {'customer_id': 'C044',
  'customer_name': 'Dana Sexton',
  'email': 'daniel85@example.net',
  'registration_date': datetime.date(2025, 4, 4),
  'customer_type': 'PREMIUM'},
 {'customer_id': 'C045',
  'customer_name': 'Anthony Kim',
  'email': 'alicia30@example.org',
  'registration_date': datetime.date(2025, 3, 12),
  'customer_type': 'VIP'},
 {'customer_id': 'C046',
  'customer_name': 'James Cross',
  'email': 'peteranderson@example.org',
  'registration_date': datetime.date(2024, 9, 6),
  'customer_type': 'REGULAR'},
 {'customer_id': 'C047',
  'customer_name': 'Victor Flores',
  'email': 'qfrench@example.net',
  'registration_date': datetime.date(2026, 6, 5),
  'customer_type': 'PREMIUM'},
 {'customer_id': 'C048',
  'customer_name': 'Angel Benjamin',
  'email': 'jacquelinegould@example.net',
  'registration_date': datetime.date(2026, 4, 13),
  'customer_type': 'PREMIUM'},
 {'customer_id': 'C049',
  'customer_name': 'Kenneth Wagner',
  'email': 'thomas49@example.com',
  'registration_date': datetime.date(2026, 4, 1),
  'customer_type': 'REGULAR'},
 {'customer_id': 'C050',
  'customer_name': 'Kenneth Coffey',
  'email': 'duranrose@example.com',
  'registration_date': datetime.date(2024, 10, 26),
  'customer_type': 'PREMIUM'},
 {'customer_id': 'C051',
  'customer_name': 'David Perez',
  'email': 'aandrade@example.org',
  'registration_date': datetime.date(2026, 6, 25),
  'customer_type': 'PREMIUM'},
 {'customer_id': 'C052',
  'customer_name': 'Kristen Richardson',
  'email': 'shawn56@example.com',
  'registration_date': datetime.date(2025, 4, 4),
  'customer_type': 'PREMIUM'},
 {'customer_id': 'C053',
  'customer_name': 'Dustin Stephenson',
  'email': 'mckinneysarah@example.org',
  'registration_date': datetime.date(2026, 7, 5),
  'customer_type': 'REGULAR'},
 {'customer_id': 'C054',
  'customer_name': 'Matthew Suarez',
  'email': 'blairdesiree@example.org',
  'registration_date': datetime.date(2025, 5, 27),
  'customer_type': 'PREMIUM'},
 {'customer_id': 'C055',
  'customer_name': 'Melissa Jordan',
  'email': 'rgrant@example.com',
  'registration_date': datetime.date(2025, 9, 9),
  'customer_type': 'PREMIUM'},
 {'customer_id': 'C056',
  'customer_name': 'Theresa Jefferson',
  'email': 'whiteglen@example.com',
  'registration_date': datetime.date(2025, 9, 4),
  'customer_type': 'REGULAR'},
 {'customer_id': 'C057',
  'customer_name': 'Carl Burton',
  'email': 'newmanbrian@example.net',
  'registration_date': datetime.date(2026, 5, 7),
  'customer_type': 'VIP'},
 {'customer_id': 'C058',
  'customer_name': 'Christopher Richards',
  'email': 'kramirez@example.org',
  'registration_date': datetime.date(2024, 11, 2),
  'customer_type': 'VIP'},
 {'customer_id': 'C059',
  'customer_name': 'Julie Bell',
  'email': 'velliott@example.com',
  'registration_date': datetime.date(2024, 12, 17),
  'customer_type': 'REGULAR'},
 {'customer_id': 'C060',
  'customer_name': 'Joshua Evans',
  'email': 'campospaula@example.net',
  'registration_date': datetime.date(2026, 1, 11),
  'customer_type': 'VIP'},
 {'customer_id': 'C061',
  'customer_name': 'Jessica Schmidt',
  'email': 'michaelowen@example.org',
  'registration_date': datetime.date(2024, 10, 21),
  'customer_type': 'VIP'},
 {'customer_id': 'C062',
  'customer_name': 'Peter Blair',
  'email': 'arthurwelch@example.com',
  'registration_date': datetime.date(2025, 3, 5),
  'customer_type': 'VIP'},
 {'customer_id': 'C063',
  'customer_name': 'Jennifer Ramos',
  'email': 'cynthia73@example.net',
  'registration_date': datetime.date(2024, 7, 25),
  'customer_type': 'VIP'},
 {'customer_id': 'C064',
  'customer_name': 'John Beltran',
  'email': 'franciscobowman@example.com',
  'registration_date': datetime.date(2024, 12, 29),
  'customer_type': 'REGULAR'},
 {'customer_id': 'C065',
  'customer_name': 'Holly Huerta',
  'email': 'elee@example.org',
  'registration_date': datetime.date(2024, 11, 11),
  'customer_type': 'VIP'},
 {'customer_id': 'C066',
  'customer_name': 'Jason Lara',
  'email': 'belindareed@example.com',
  'registration_date': datetime.date(2025, 11, 27),
  'customer_type': 'PREMIUM'},
 {'customer_id': 'C067',
  'customer_name': 'Lisa Kim',
  'email': 'kwhite@example.com',
  'registration_date': datetime.date(2025, 5, 5),
  'customer_type': 'VIP'},
 {'customer_id': 'C068',
  'customer_name': 'Amber Sanchez',
  'email': 'jefferydrake@example.com',
  'registration_date': datetime.date(2026, 2, 25),
  'customer_type': 'REGULAR'},
 {'customer_id': 'C069',
  'customer_name': 'Frank Bailey',
  'email': 'nicole12@example.org',
  'registration_date': datetime.date(2025, 8, 16),
  'customer_type': 'VIP'},
 {'customer_id': 'C070',
  'customer_name': 'Debra Randall',
  'email': 'tcook@example.net',
  'registration_date': datetime.date(2024, 11, 2),
  'customer_type': 'VIP'},
 {'customer_id': 'C071',
  'customer_name': 'Samuel Hall',
  'email': 'johnsoncharlene@example.net',
  'registration_date': datetime.date(2024, 12, 5),
  'customer_type': 'VIP'},
 {'customer_id': 'C072',
  'customer_name': 'Ryan Contreras',
  'email': 'edwardmartin@example.org',
  'registration_date': datetime.date(2024, 8, 19),
  'customer_type': 'VIP'},
 {'customer_id': 'C073',
  'customer_name': 'Denise Knox',
  'email': 'collin72@example.com',
  'registration_date': datetime.date(2026, 5, 17),
  'customer_type': 'PREMIUM'},
 {'customer_id': 'C074',
  'customer_name': 'William Smith',
  'email': 'james85@example.net',
  'registration_date': datetime.date(2026, 7, 4),
  'customer_type': 'REGULAR'},
 {'customer_id': 'C075',
  'customer_name': 'Theodore Wright Jr.',
  'email': 'mmartinez@example.org',
  'registration_date': datetime.date(2026, 4, 16),
  'customer_type': 'REGULAR'},
 {'customer_id': 'C076',
  'customer_name': 'Jose Phelps',
  'email': 'derekacosta@example.org',
  'registration_date': datetime.date(2026, 5, 5),
  'customer_type': 'PREMIUM'},
 {'customer_id': 'C077',
  'customer_name': 'Holly Peck',
  'email': 'rhodeswilliam@example.net',
  'registration_date': datetime.date(2026, 3, 22),
  'customer_type': 'REGULAR'},
 {'customer_id': 'C078',
  'customer_name': 'Sonya Rivers',
  'email': 'yreed@example.net',
  'registration_date': datetime.date(2026, 1, 30),
  'customer_type': 'PREMIUM'},
 {'customer_id': 'C079',
  'customer_name': 'Amy Nelson PhD',
  'email': 'carterolivia@example.org',
  'registration_date': datetime.date(2025, 4, 29),
  'customer_type': 'REGULAR'},
 {'customer_id': 'C080',
  'customer_name': 'Rachael Randall',
  'email': 'markmurray@example.org',
  'registration_date': datetime.date(2025, 8, 1),
  'customer_type': 'VIP'},
 {'customer_id': 'C081',
  'customer_name': 'Frederick Barnes',
  'email': 'brittneymurray@example.net',
  'registration_date': datetime.date(2024, 11, 27),
  'customer_type': 'REGULAR'},
 {'customer_id': 'C082',
  'customer_name': 'James Landry',
  'email': 'margaretmoore@example.com',
  'registration_date': datetime.date(2026, 2, 20),
  'customer_type': 'VIP'},
 {'customer_id': 'C083',
  'customer_name': 'Daniel Mitchell',
  'email': 'wrightlindsey@example.net',
  'registration_date': datetime.date(2026, 2, 12),
  'customer_type': 'REGULAR'},
 {'customer_id': 'C084',
  'customer_name': 'Charles Lambert',
  'email': 'codybrooks@example.net',
  'registration_date': datetime.date(2026, 1, 12),
  'customer_type': 'VIP'},
 {'customer_id': 'C085',
  'customer_name': 'Justin Torres',
  'email': 'adrianyork@example.net',
  'registration_date': datetime.date(2024, 11, 20),
  'customer_type': 'REGULAR'},
 {'customer_id': 'C086',
  'customer_name': 'Whitney Berg',
  'email': 'derrick80@example.net',
  'registration_date': datetime.date(2025, 3, 8),
  'customer_type': 'REGULAR'},
 {'customer_id': 'C087',
  'customer_name': 'Isaac Mendoza',
  'email': 'sharonsmith@example.com',
  'registration_date': datetime.date(2026, 1, 1),
  'customer_type': 'VIP'},
 {'customer_id': 'C088',
  'customer_name': 'Benjamin Mcclain',
  'email': 'taylor25@example.org',
  'registration_date': datetime.date(2026, 3, 15),
  'customer_type': 'REGULAR'},
 {'customer_id': 'C089',
  'customer_name': 'Sarah Pratt',
  'email': 'vjohnson@example.com',
  'registration_date': datetime.date(2026, 5, 18),
  'customer_type': 'REGULAR'},
 {'customer_id': 'C090',
  'customer_name': 'Lisa Foster',
  'email': 'barberdana@example.com',
  'registration_date': datetime.date(2026, 7, 3),
  'customer_type': 'PREMIUM'},
 {'customer_id': 'C091',
  'customer_name': 'Alyssa Hicks',
  'email': 'hughesrobert@example.org',
  'registration_date': datetime.date(2026, 5, 28),
  'customer_type': 'PREMIUM'},
 {'customer_id': 'C092',
  'customer_name': 'Jordan Hughes',
  'email': 'sbuchanan@example.org',
  'registration_date': datetime.date(2026, 5, 29),
  'customer_type': 'PREMIUM'},
 {'customer_id': 'C093',
  'customer_name': 'Darren Lee',
  'email': 'franklinpaul@example.com',
  'registration_date': datetime.date(2025, 6, 25),
  'customer_type': 'PREMIUM'},
 {'customer_id': 'C094',
  'customer_name': 'Derrick Beltran',
  'email': 'eclark@example.com',
  'registration_date': datetime.date(2026, 1, 31),
  'customer_type': 'PREMIUM'},
 {'customer_id': 'C095',
  'customer_name': 'Raymond Reed',
  'email': 'jameslopez@example.org',
  'registration_date': datetime.date(2026, 2, 26),
  'customer_type': 'VIP'},
 {'customer_id': 'C096',
  'customer_name': 'Nicholas Sanchez',
  'email': 'taylor33@example.com',
  'registration_date': datetime.date(2025, 3, 28),
  'customer_type': 'PREMIUM'},
 {'customer_id': 'C097',
  'customer_name': 'Jeremy Pena',
  'email': 'ogonzalez@example.com',
  'registration_date': datetime.date(2024, 10, 28),
  'customer_type': 'VIP'},
 {'customer_id': 'C098',
  'customer_name': 'Daniel Hernandez',
  'email': 'lauravalencia@example.net',
  'registration_date': datetime.date(2026, 2, 18),
  'customer_type': 'REGULAR'},
 {'customer_id': 'C099',
  'customer_name': 'Brian Huff',
  'email': 'jacobortiz@example.org',
  'registration_date': datetime.date(2025, 1, 2),
  'customer_type': 'PREMIUM'},
 {'customer_id': 'C100',
  'customer_name': 'Jason Erickson',
  'email': 'mevans@example.org',
  'registration_date': datetime.date(2025, 2, 17),
  'customer_type': 'VIP'},
 {'customer_id': 'C101',
  'customer_name': 'Nicholas Parker',
  'email': 'yschultz@example.com',
  'registration_date': datetime.date(2026, 6, 5),
  'customer_type': 'PREMIUM'},
 {'customer_id': 'C102',
  'customer_name': 'Steve Bell',
  'email': 'greed@example.org',
  'registration_date': datetime.date(2026, 4, 22),
  'customer_type': 'REGULAR'},
 {'customer_id': 'C103',
  'customer_name': 'Andrew Rodgers',
  'email': 'nrichards@example.com',
  'registration_date': datetime.date(2026, 3, 27),
  'customer_type': 'VIP'},
 {'customer_id': 'C104',
  'customer_name': 'Andrew Salas',
  'email': 'kennedyedwin@example.com',
  'registration_date': datetime.date(2024, 7, 26),
  'customer_type': 'REGULAR'},
 {'customer_id': 'C105',
  'customer_name': 'Jose Sanchez',
  'email': 'curryjacob@example.org',
  'registration_date': datetime.date(2024, 7, 25),
  'customer_type': 'VIP'},
 {'customer_id': 'C106',
  'customer_name': 'Nicole Franklin',
  'email': 'kevin04@example.net',
  'registration_date': datetime.date(2024, 12, 28),
  'customer_type': 'REGULAR'},
 {'customer_id': 'C107',
  'customer_name': 'Shelia Smith',
  'email': 'joshualyons@example.org',
  'registration_date': datetime.date(2025, 4, 23),
  'customer_type': 'REGULAR'},
 {'customer_id': 'C108',
  'customer_name': 'Carrie Porter',
  'email': 'jameswashington@example.com',
  'registration_date': datetime.date(2024, 12, 10),
  'customer_type': 'REGULAR'},
 {'customer_id': 'C109',
  'customer_name': 'Harold Reese',
  'email': 'tmiller@example.net',
  'registration_date': datetime.date(2026, 7, 3),
  'customer_type': 'REGULAR'},
 {'customer_id': 'C110',
  'customer_name': 'Emily Gray',
  'email': 'xcox@example.net',
  'registration_date': datetime.date(2024, 10, 26),
  'customer_type': 'VIP'},
 {'customer_id': 'C111',
  'customer_name': 'Kenneth Moore',
  'email': 'tarabooker@example.net',
  'registration_date': datetime.date(2026, 2, 7),
  'customer_type': 'VIP'},
 {'customer_id': 'C112',
  'customer_name': 'David Daniel',
  'email': 'rosariomichelle@example.org',
  'registration_date': datetime.date(2026, 5, 16),

In [14]:
customers_df = pd.DataFrame(customers)

customers_df

,customer_id,customer_name,email,registration_date,customer_type
0,C001,Janice Sherman,alyssawhite@example.org,2025-12-18,PREMIUM
1,C002,Stephanie Gonzalez,vbaker@example.org,2024-12-30,PREMIUM
2,C003,Yolanda Hernandez DVM,rpratt@example.com,2024-07-25,PREMIUM
3,C004,Brandi Gay,rogersruth@example.net,2025-04-19,PREMIUM
4,C005,Samantha Pearson,blevine@example.org,2026-03-12,REGULAR
...,...,...,...,...,...
995,C996,Krista Vargas,garciajulie@example.org,2025-03-02,REGULAR
996,C997,Joanna Whitehead,kathrynmorris@example.org,2025-07-10,REGULAR
997,C998,Zachary Hayes,melindamatthews@example.net,2026-05-17,VIP
998,C999,Dennis Ross,jeremiah56@example.com,2025-04-19,REGULAR
999,C1000,Andrew Clark,carterelizabeth@example.org,2025-11-28,REGULAR

In [15]:
customers_df.to_csv("customers.csv", index=False)

print("customers.csv created successfully!")

customers.csv created successfully!

In [16]:
product_names = [
    "Laptop", "Mobile", "Headphones", "Keyboard", "Mouse",
    "T-Shirt", "Jeans", "Shoes", "Jacket", "Watch",
    "Book", "Notebook", "Chair", "Table", "Bottle",
    "Bag", "Camera", "Speaker", "Monitor", "Printer"
]

categories = {
    "Electronics": ["Laptop", "Mobile", "Headphones", "Keyboard", "Mouse", "Camera", "Speaker", "Monitor", "Printer"],
    "Clothing": ["T-Shirt", "Jeans", "Shoes", "Jacket"],
    "Books": ["Book", "Notebook"],
    "Home": ["Chair", "Table", "Bottle", "Bag"]
}

In [17]:
products = []

for i in range(500):

    category = random.choice(list(categories.keys()))
    product = random.choice(categories[category])

    products.append({
        "product_id": f"P{i+1:03}",
        "product_name": product,
        "category": category,
        "subcategory": product,
        "cost_price": random.randint(100,50000)
    })

products_df = pd.DataFrame(products)

products_df.head()

  product_id product_name  category subcategory  cost_price
0       P001       Jacket  Clothing      Jacket        1290
1       P002        Table      Home       Table       48141
2       P003     Notebook     Books    Notebook       20363
3       P004        Chair      Home       Chair       39327
4       P005        Chair      Home       Chair       31419

In [18]:
products_df.to_csv("products.csv", index=False)

print("products.csv created successfully!")

products.csv created successfully!

In [19]:
statuses = ["PLACED", "SHIPPED", "DELIVERED", "CANCELLED", "RETURNED"]

regions = ["North", "South", "East", "West"]

In [20]:
orders = []

for i in range(10000):

    orders.append({

        "order_id": f"O{i+1:05}",

        "customer_id": f"C{random.randint(1,1000):03}",

        "order_date": fake.date_time_between(start_date="-2y", end_date="now"),

        "status": random.choice(statuses),

        "region_code": random.choice(regions)

    })

orders_df = pd.DataFrame(orders)

orders_df.head()

  order_id customer_id          order_date     status region_code
0   O00001        C858 2025-07-19 17:34:59   RETURNED        East
1   O00002        C655 2026-03-21 13:55:00  CANCELLED       South
2   O00003        C725 2026-06-24 10:53:31  CANCELLED        West
3   O00004        C164 2025-12-07 14:19:51  DELIVERED       South
4   O00005        C783 2024-09-01 21:52:39  CANCELLED       North

In [21]:
orders_df.to_csv("orders.csv", index=False)

print("orders.csv created successfully!")

orders.csv created successfully!

In [22]:
order_items = []

for i in range(30000):

    order_items.append({

        "item_id": f"I{i+1:05}",

        "order_id": f"O{random.randint(1,10000):05}",

        "product_id": f"P{random.randint(1,500):03}",

        "quantity": random.randint(1,5),

        "unit_price": random.randint(100,50000),

        "discount_percent": random.randint(0,50)

    })

order_items_df = pd.DataFrame(order_items)

order_items_df.head()

  item_id order_id product_id  quantity  unit_price  discount_percent
0  I00001   O06480       P208         3       17589                12
1  I00002   O02398       P361         4       33166                44
2  I00003   O03804       P459         3       28566                15
3  I00004   O00675       P119         3       33057                45
4  I00005   O01313       P200         3       31857                 7

In [23]:
order_items_df.to_csv("order_items.csv", index=False)

print("order_items.csv created successfully!")

order_items.csv created successfully!

In [18]:
orders_df.head()

  order_id customer_id          order_date     status region_code
0   O00001        C039 2025-05-04 16:34:10   RETURNED       North
1   O00002        C658 2025-12-29 19:48:30    SHIPPED       North
2   O00003        C636 2025-03-15 11:17:07     PLACED       South
3   O00004        C724 2026-01-01 04:56:18     PLACED        East
4   O00005        C426 2025-02-12 04:21:16  DELIVERED       South